apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../c3

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: ControlCenter
    path: c3.yml
