apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfk-storage-delete
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---