apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infra/observability/kraft
  - ../../../base/infra/observability/kafka
  - ../../../base/infra/observability/c3

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: ControlCenter
    patch: |-
      - op: add
        path: /spec/configOverrides
        value:
          server:
            - confluent.controlcenter.mds.client.max.requests.queued.per.destination=2048
            - confluent.controlcenter.mode.enable=management
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KRaftController
    patch: |-
      - op: replace
        path: /spec/dataVolumeCapacity
        value: 25Gi 
      - op: replace
        path: /spec/podTemplate/resources/limits
        value:
          cpu: 500m
          memory: 1Gi      

  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Kafka
    patch: |-
      - op: replace
        path: /spec/services/mds/externalAccess/nodePort/host
        value: mds.dev.gke.nermdev.io
      - op: replace
        path: /spec/listeners/external/externalAccess/loadBalancer/domain
        value: dev.gke.nermdev.io
      - op: add
        path: /spec/podTemplate/resources/limits
        value:
          cpu: 2.0
          memory: 4Gi
      - op: add
        path: /spec/configOverrides
        value: 
          server:
            - kafka.rest.client.client.id=dev.kafkarestclient
            - kafka.rest.admin.client.id=dev.kafkarestadmin
            - kafka.rest.admin.ssl.keystore.location=/mnt/sslcerts/keystore.p12
            - kafka.rest.admin.ssl.keystore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
            - kafka.rest.admin.ssl.key.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
            - kafka.rest.admin.ssl.truststore.location=/mnt/sslcerts/truststore.p12
            - kafka.rest.admin.ssl.truststore.password=${file:/mnt/sslcerts/jksPassword.txt:jksPassword}
            - auto.create.topics.enable=true
            - confluent.cluster.link.enable=true
            - confluent.balancer.enable=false
            - confluent.metrics.reporter.publish.ms=60000
            - confluent.metrics.reporter.topic.retention.ms=7200000
            - min.insync.replicas=2
            - log.retention.hours=12
      - op: add
        path: /spec/telemetry
        value:
          global: false
          
