apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-sink
  annotations:
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
  labels:
    app: event-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-sink
  template:
    metadata:
      annotations:
        prometheus.io/port: "7778"
        prometheus.io/scrape: "true"
      labels:
        app: event-sink
    spec:
      containers:
        - name: event-sink
          image: registry.nermdev.io/apps/event-sink
          imagePullPolicy: Always
          volumeMounts:
            - name: kafka-secrets
              mountPath: /mnt/kafka-secrets
            - name: tls
              mountPath: /mnt/tls
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1.0
              memory: 516Mi
      volumes:
        - name: kafka-secrets
          secret:
            secretName: kafka-secrets
        - name: tls
          secret:
            secretName: tls-nermin
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - event-sink
              topologyKey: "kubernetes.io/hostname"