apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  layer: integrity

resources:
  - ../../../base/vote-integrity

configMapGenerator:
  - name: vi-cfg
    behavior: create
    files:
      - application.properties

