apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infra/storageclass/local
  - ../../../base/infra/openldap
  - ../../../base/infra/prometheus
  - ../../../base/infra/grafana
  - ../../../base/infra/operator
  - ../../../base/infra/mongodb