apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  layer: integrity

resources:
  - ../../../base/election-ttl

configMapGenerator:
  - name: ttl-cfg
    behavior: create
    files:
      - application.properties
