apiVersion: v1
kind: Service
metadata:
  name: ttl-svc
  labels:
    app: election-ttl
spec:
  selector:
    app: election-ttl
  ports:
    - port: 7778
      name: exporter
      protocol: TCP
    - port: 7203
      name: jmx
      protocol: TCP
