kafka:
  properties:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    bootstrap.servers: bootstrap.local.nermdev.io:443
    security.protocol: SASL_SSL
    sasl.mechanism: PLAIN
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{file:/Users/ndedovic/nermdev-secrets.txt:username}" password="{file:/Users/ndedovic/nermdev-secrets.txt:password}";
    ssl.truststore.location: /Users/ndedovic/PycharmProjects/homelab/workspace/kafka/auth/nermin/truststore.jks
    ssl.truststore.password: {file:/Users/ndedovic/nermdev-secrets.txt:trust_password}
  consumer:
    group.id: test.event.sink
    auto.offset.reset: earliest
    enable.auto.commit: false
    poll.duration: 500
  consumer-topics:
    - test.election.requests
    - test.election.votes

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}
      database: edv
