kafka:
  properties:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    bootstrap.servers: kafka.cfk.svc.cluster.local:9093
    security.protocol: SASL_PLAINTEXT
    sasl.mechanism: PLAIN
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{file:/mnt/kafka-secrets/secrets.txt:username}" password="{file:/mnt/kafka-secrets/secrets.txt:password}";
    schema.registry.url: https://sr.cfk.svc.cluster.local:8081
    schema.registry.basic.auth.user.info: "{file:/mnt/kafka-secrets/secrets.txt:username}:{file:/mnt/kafka-secrets/secrets.txt:password}"
    schema.registry.basic.auth.credentials.source: USER_INFO
    schema.registry.ssl.truststore.location: /mnt/tls/truststore.jks
    schema.registry.ssl.truststore.password: {file:/mnt/kafka-secrets/secrets.txt:trust_password}
    specific.avro.reader: true
  consumer:
    group.id: test.event.sink
    auto.offset.reset: earliest
    enable.auto.commit: false
    poll.duration: 500
  consumer-topics:
    - edv.election.events

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}
      database: edv
