steps:
  - group: ":java::building_construction: JAVA :hammer:"
    steps:
      - label: "Compile / Build / Test / Package :maven::java:"
        commands:
          - mvn clean install
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
                - "$HOME/.m2:$HOME/.m2"


  - group: ":k8s: Component deployment validation :hammer:"
    steps:
      - label: ":gandalf: Deploy-validation : election-integrity :gandalf:"
        commands:
          - kustomize build deploy/overlay/test/election-integrity > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

      - label: ":gandalf: Deploy-validation : event-sink :gandalf:"
        commands:
          - kustomize build deploy/overlay/test/event-sink > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

      - label: ":gandalf: Deploy-validation : query-service :gandalf:"
        commands:
          - kustomize build deploy/overlay/test/query-service > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

  - group: ":k8s: Environment deploy validation :hammer:"
    steps:
      - label: ":gandalf: test environment :gandalf:"
        commands:
          - kustomize build deploy/environment/test > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true