steps:
  - group: ":java::building_construction: JAVA :hammer:"
    steps:
      - label: "Compile / Build / Test / Package :maven::java:"
        commands:
          - mvn clean install
        artifact_paths: "**/target/*.jar"
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
                - "$HOME/.m2:$HOME/.m2"


  - group: ":k8s: Component deployment validation :hammer:"
    steps:
      - label: ":gandalf: Deploy-validation : vote-integrity :gandalf:"
        commands:
          - kustomize build deploy/overlay/gke/vote-integrity > /dev/null
          - kustomize build deploy/overlay/local/vote-integrity > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

      - label: ":gandalf: Deploy-validation : election-integrity :gandalf:"
        commands:
          - kustomize build deploy/overlay/gke/election-integrity > /dev/null
          - kustomize build deploy/overlay/local/election-integrity > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

      - label: ":gandalf: Deploy-validation : event-sink :gandalf:"
        commands:
          - kustomize build deploy/overlay/gke/event-sink > /dev/null
          - kustomize build deploy/overlay/local/event-sink > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

      - label: ":gandalf: Deploy-validation : query-service :gandalf:"
        commands:
          - kustomize build deploy/overlay/gke/query-service > /dev/null
          - kustomize build deploy/overlay/local/query-service > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

  - group: ":k8s: Environment deploy validation :hammer:"
    steps:
      - label: ":gandalf: GKE environment :gandalf:"
        commands:
          - echo "edv" > /tmp/gib.txt
          - kubectl create secret generic license-secret -n cfk-operator --from-file=license.txt=/tmp/gib.txt --dry-run=client -o yaml > deploy/base/infra/operator/license-secret.yml
          - kustomize build --enable-helm deploy/environment/gke/00_infra_init > /dev/null
          - kustomize build deploy/environment/gke/01_infra > /dev/null
          - kustomize build deploy/environment/gke/02_apps > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true

      - label: ":gandalf: local environment :gandalf:"
        commands:
          - echo "edv" > /tmp/gib.txt
          - kubectl create secret generic license-secret -n cfk-operator --from-file=license.txt=/tmp/gib.txt --dry-run=client -o yaml > deploy/base/infra/operator/license-secret.yml
          - kustomize build --enable-helm deploy/environment/local/00_infra_init > /dev/null
          - kustomize build deploy/environment/local/01_infra > /dev/null
          - kustomize build deploy/environment/local/02_apps > /dev/null
        plugins:
          - docker#v5.8.0:
              image: dedovicnermin/buildkite-j17:0.0.2
              propagate-uid-gid: true