apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  project: edv

resources:
  - ../../../overlay/local/topics
  - ../../../overlay/local/election-integrity
  - ../../../overlay/local/vote-integrity
  - ../../../overlay/local/event-sink
  - ../../../overlay/local/query-service
  - ../../../overlay/local/election-ttl

images:
  - name: dedovicnermin/election-integrity
    newTag: 0.0.4
  - name: dedovicnermin/vote-integrity
    newTag: 0.0.8
  - name: dedovicnermin/event-sink
    newTag: 0.0.3
  - name: dedovicnermin/query-service
    newTag: 0.0.4
  - name: dedovicnermin/election-ttl
    newTag: 0.0.2
