apiVersion: v1
kind: Service
metadata:
  name: vi-svc
  labels:
    app: vintegrity
spec:
  selector:
    app: vintegrity
  ports:
    - port: 7778
      name: exporter
      protocol: TCP
    - port: 7203
      name: jmx
      protocol: TCP
