apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vintegrity
  annotations:
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
  labels:
    app: vintegrity
spec:
  selector:
    matchLabels:
      app: vintegrity
  serviceName: vi-svc
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      annotations:
        prometheus.io/port: "7778"
        prometheus.io/scrape: "true"
      labels:
        app: vintegrity
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - vintegrity
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        fsGroup: 54321
        runAsUser: 1000
      containers:
        - name: vintegrity
          image: dedovicnermin/vote-integrity
          args:
            - /mnt/application/application.properties
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: vintegrity-state
              mountPath: /mnt/data/
              subPath: vintegrity
            - name: app-config
              mountPath: /mnt/application
            - name: tls
              mountPath: /mnt/sslcerts
          resources:
            requests:
              cpu: 100m
              memory: 132Mi
            limits:
              cpu: 100m
              memory: 132Mi
      volumes:
        - name: app-config
          configMap:
            name: vi-cfg
        - name: tls
          secret:
            secretName: tls-nermin
  volumeClaimTemplates:
    - metadata:
        name: vintegrity-state
      spec:
        storageClassName: cfk-storage-delete
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 164Mi