apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml

helmCharts:
  - name: prometheus
    namespace: monitoring
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    includeCRDs: true
    version: 22.7.0
    valuesFile: values.yml
