apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-env
data:
  MONGO_INITDB_DATABASE: "edv"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin-secret"
  MONGO_USER: "edv"
  MONGO_PASSWORD: "edv-secret"
  ELECTION_COLLECTION: "election"
  USER_COLLECTION: "users"