apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-scripts
data:
  mongo-init.js: |
    db = db.getSiblingDB('admin')
    db.auth(
        process.env.MONGO_INITDB_ROOT_USERNAME,
        process.env.MONGO_INITDB_ROOT_PASSWORD
    );

    db = db.getSiblingDB(process.env.MONGO_INITDB_DATABASE);
    db.createUser({
        user: process.env.MONGO_USER,
        pwd: process.env.MONGO_PASSWORD,
        roles: [{
            role: 'readWrite',
            db: process.env.MONGO_INITDB_DATABASE
        }]
    });

    db.createCollection(process.env.ELECTION_COLLECTION);
    db.createCollection(process.env.USER_COLLECTION);