apiVersion: v1
kind: Service
metadata:
  name: election-integrity
  labels:
    app: election-integrity
spec:
  selector:
    app: election-integrity
  ports:
    - port: 7778
      name: exporter
      protocol: TCP
    - port: 7203
      name: jmx
      protocol: TCP