apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../kafka

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: Kafka
    path: kafka.yml
