apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/topics

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KafkaTopic
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/partitionCount
        value: 3
