apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  project: edv

resources:
  - ../../../overlay/gke/topics
  - ../../../overlay/gke/election-integrity
  - ../../../overlay/gke/vote-integrity
  - ../../../overlay/gke/event-sink
  - ../../../overlay/gke/query-service
  - ../../../overlay/gke/election-ttl

images:
  - name: dedovicnermin/election-integrity
    newTag: 0.0.3
  - name: dedovicnermin/vote-integrity
    newTag: 0.0.7
  - name: dedovicnermin/event-sink
    newTag: 0.0.2
  - name: dedovicnermin/query-service
    newTag: 0.0.3
  - name: dedovicnermin/election-ttl
    newTag: 0.0.1

