spring:
  rsocket:
    server:
      transport: websocket
      mapping-path: /cmd
      port: 7000

kafka:
  properties:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    bootstrap.servers: kafka.cfk.svc.cluster.local:9093
    security.protocol: SASL_PLAINTEXT
    sasl.mechanism: PLAIN
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="{file:/mnt/kafka-secrets/secrets.txt:username}" password="{file:/mnt/kafka-secrets/secrets.txt:password}";
  producer:
    linger.ms: 15
    acks: all
    enable.idempotence: true
  topics:
    NEW_VOTE: test.election.commands
    NEW_ELECTION: test.election.commands



