apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  layer: read

resources:
  - ../../../base/query-service

patches:
  - target:
      kind: Deployment
      name: query-service
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 264Mi
      - op: replace
        path: /spec/replicas
        value: 1