apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vi-svc.yml
  - vintegrity.yml

images:
  - name: dedovicnermin/vote-integrity
    newTag: 0.0.5

configMapGenerator:
  - name: vi-cfg
    behavior: create
    files:
      - application.properties

