apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  annotations:
    prometheus.io/port: "7778"
    prometheus.io/scrape: "true"
  labels:
    app: query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      annotations:
        prometheus.io/port: "7778"
        prometheus.io/scrape: "true"
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service
          image: registry.nermdev.io/edv/query-service
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 1.0
              memory: 256Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - query-service
              topologyKey: "kubernetes.io/hostname"