apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/namespace-dev.yml
  - license-secret.yml



helmCharts:
  - name: confluent-for-kubernetes
    repo: https://packages.confluent.io/helm
    version: 0.921.2
    releaseName: confluent-operator
    namespace: cfk-operator
    valuesFile: values.yml
    includeCRDs: true


