---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  replicas: 3
  storageClass:
    name: cfk-storage-delete
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 64Gi
  passwordEncoder:
    secretRef: password-encoder-secret
  tls:
    secretRef: tls-kafka
  authorization:
    type: rbac
    superUsers:
      - User:kafka
      - User:kraft
      - User:nermin
      - User:ANONYMOUS
  listeners:
    internal:
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: true
    external:
      authentication:
        type: ldap
      tls:
        enabled: true
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: unknown.until.built
          brokerPrefix: b
          bootstrapPrefix: bootstrap
    custom:
      - name: intldap
        port: 9094
        authentication:
          type: ldap
        tls:
          enabled: true
      - name: nonsecure
        port: 9095
        tls:
          enabled: false


  podTemplate:
    tolerations:
      - key: app
        operator: Equal
        value: infra
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - infra
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - infra

    resources:
      requests:
        cpu: 500m
        memory: 1Gi

  services:
    mds:
      externalAccess:
        type: nodePort
        nodePort:
          externalTrafficPolicy: Cluster
          host: unknown
          nodePortOffset: 30002
      authentication:
        type: bearer
      provider:
        ldap:
          address: ldap://ldap.cfk-operator.svc.cluster.local:389
          authentication:
            type: simple
            simple:
              secretRef: ldaps-user
          configurations:
            groupNameAttribute: cn
            groupObjectClass: posixGroup
            groupMemberAttribute: memberUid
            groupMemberAttributePattern: cn=(.*),ou=users,dc=nermdev,dc=io
            groupSearchBase: ou=groups,dc=nermdev,dc=io
            userNameAttribute: cn
            userObjectClass: inetOrgPerson
            userSearchBase: ou=users,dc=nermdev,dc=io
        type: ldap
      tokenKeyPair:
        secretRef: mds-token
  dependencies:
    kRaftController:
      controllerListener:
        tls:
          enabled: true
        authentication:
          type: mtls
          principalMappingRules:
            - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
      clusterRef:
        name: kraft
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: mds-kafka
