apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  project: edv

resources:
  - ../../overlay/local/topics
  - ../../overlay/local/election-integrity
  - ../../overlay/local/vote-integrity
  - ../../overlay/local/event-sink
  - ../../overlay/local/query-service

images:
  - name: dedovicnermin/election-integrity
    newTag: 0.0.2
  - name: dedovicnermin/vote-integrity
    newTag: 0.0.6
  - name: dedovicnermin/event-sink
    newTag: 0.0.1
  - name: dedovicnermin/query-service
    newTag: 0.0.1

