apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: election.votes.raw
spec:
  replicas: 1
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default
