{
 "title": "EDV",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "election-integrity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{app=\"eintegrity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vote-integrity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{app=\"vintegrity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "query-service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "up{app=\"query-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "event-sink",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "up{app=\"event-sink\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}