apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraft
  annotations:
    platform.confluent.io/broker-id-offset: "1000"
spec:
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  replicas: 3
  dataVolumeCapacity: 10Gi
  storageClass:
    name: cfk-storage-delete
  tls:
    secretRef: tls-kraft
  listeners:
    controller:
      tls:
        enabled: true
      authentication:
        type: mtls
        principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
  podTemplate:
    tolerations:
      - key: app
        operator: Equal
        value: infra
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - infra
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - infra

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi