apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  layer: integrity

resources:
  - ../../../base/election-integrity

configMapGenerator:
  - name: ei-cfg
    behavior: create
    files:
      - application.properties

patches:
  - target:
      kind: Deployment
      name: eintegrity
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 216Mi
      - op: replace
        path: /spec/replicas
        value: 1
